<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<style type="text/css">
		body {
			font-family: Arial;
			font-size: 14px;
		}
	</style>
</head>
<body yahoo bgcolor="#fff">
<table width="100%" bgcolor="#fff" border="0" cellpadding="0" cellspacing="0" style="margin: 0; padding: 0; min-width: 100%!important; font-family: Arial; font-size: 14px">
	<tr>
		<td>
			<table class="content" align="center" cellpadding="0" cellspacing="0" border="0" style="width: 100%; max-width: 600px;">
				<tr>
					<td style="padding: 30px 15px 20px 15px;" colspan="2">
						<?= $this->content ?>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
</body>
</html>